// packages/govie-component-library/ds/src/components/button/button.tsx
import { clsx } from 'clsx';
import {
  isButtonDisabled,
  getSizeClass,
  getVariantAppearanceClass,
} from './helpers.js';
import { ButtonProps } from './types.js';
import { Component, Prop, h, Element } from '@stencil/core';

@Component({
  tag: 'govie-button',
  shadow: false,
})
export class GovieButton {
  @Element() el!: HTMLElement;

  @Prop() variant?: ButtonProps['variant'];
  @Prop() appearance?: ButtonProps['appearance'];
  @Prop() size?: ButtonProps['size'];

  @Prop({ reflect: true }) disabled = false;

  @Prop({ attribute: 'class' }) class?: string;

  private getForwardedAttrs() {
    const excluded = new Set([
      'variant',
      'appearance',
      'size',
      'disabled',
      'class',
    ]);

    const attrs: Record<string, string> = {};
    for (const attr of Array.from(this.el.attributes)) {
      if (!excluded.has(attr.name)) attrs[attr.name] = attr.value;
    }
    return attrs;
  }

  render() {
    const forwarded = this.getForwardedAttrs();

    return (
      <button
        {...forwarded}
        aria-disabled={this.disabled ? 'true' : null}
        disabled={this.disabled}
        class={clsx(
          'gi-btn',
          getVariantAppearanceClass({
            disabled: this.disabled,
            variant: this.variant,
            appearance: this.appearance,
          }),
          isButtonDisabled({
            disabled: this.disabled,
            variant: this.variant,
            appearance: this.appearance,
          }),
          getSizeClass(this.size),
          this.class,
        )}
      >
        <slot></slot>
      </button>
    );
  }
}

// packages/react/ds/src/button/button.tsx
'use client';
import {
  isButtonDisabled,
  getSizeClass,
  getVariantAppearanceClass,
} from './helpers.js';
import { ButtonProps } from './types.js';

export const Button = ({
  variant,
  appearance,
  size,
  disabled,
  children,
  onClick,
  type,
  form,
  value,
}: ButtonProps) => {
  return (
    <button
      type={type}
      form={form}
      value={value}
      data-testid={`govieButton-${appearance}-${variant}-${size}-${disabled ? 'disabled' : ''}`}
      onClick={onClick}
      className={`gi-btn ${getVariantAppearanceClass({ disabled, variant, appearance })} ${getSizeClass(size)} ${isButtonDisabled({ disabled, variant, appearance })}`}
    >
      {children}
    </button>
  );
};
