// packages/react/src/paragraph/paragraph.tsx
export type ParagraphAs = 'p' | 'span';
export type ParagraphAsNext = 'p';
import { Text } from '../atoms';
export type ParagraphSize = 'xl' | 'lg' | 'md' | 'sm';
export type ParagraphAlign = 'start' | 'center' | 'end' | 'justify';
export type ParagraphWhitespace =
  | 'normal'
  | 'pre'
  | 'pre-wrap'
  | 'break-spaces';

type ParagraphPropsBase = {
  size?: ParagraphSize;
  align?: ParagraphAlign;
  whitespace?: ParagraphWhitespace;
  children: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  ariaLabel?: string;
  id?: string;
  dataTestid?: string;
};

export type ParagraphProps =
  | (ParagraphPropsBase & { as?: 'p' })
  | (ParagraphPropsBase & {
      /** @deprecated Use `<Text />` instead of `<Paragraph as="span" />`. */
      as: 'span';
    });

export function Paragraph({
  as: As = 'p',
  size = 'md',
  align = 'start',
  whitespace = 'normal',
  children,
  style,
  className,
  id,
  ariaLabel,
  dataTestid,
}: ParagraphProps) {
  const sizeClass = (() => {
    switch (size) {
      case 'xl': {
        return As === 'p' ? 'gi-paragraph-xl' : 'gi-span-xl';
      }
      case 'lg': {
        return As === 'p' ? 'gi-paragraph-lg' : 'gi-span-lg';
      }
      case 'sm': {
        return As === 'p' ? 'gi-paragraph-sm' : 'gi-span-sm';
      }
      default: {
        return As === 'p' ? 'gi-paragraph-md' : 'gi-span-md';
      }
    }
  })();

  const alignClass = (() => {
    switch (align) {
      case 'center': {
        return 'gi-text-center';
      }
      case 'end': {
        return 'gi-text-end';
      }
      case 'justify': {
        return 'gi-text-justify';
      }
      default: {
        return 'gi-text-start';
      }
    }
  })();

  const whitespaceClass = (() => {
    switch (whitespace) {
      case 'pre': {
        return 'gi-whitespace-pre';
      }
      case 'pre-wrap': {
        return 'gi-whitespace-pre-wrap';
      }
      case 'break-spaces': {
        return 'gi-whitespace-break-spaces';
      }
      default: {
        return 'gi-whitespace-normal';
      }
    }
  })();
  if (As === 'span') {
    return (
      <Text
        size={size}
        whitespace={whitespace}
        className={className}
        styles={style}
        id={id}
        dataTestid={dataTestid}
      >
        {children}
      </Text>
    );
  }
  return (
    <p
      className={`${sizeClass} ${alignClass} ${whitespaceClass} ${className || ''}`}
      aria-label={ariaLabel}
      style={style}
      id={id}
      data-testid={dataTestid}
    >
      {children}
    </p>
  );
}

// packages/govie-component-library/ds/src/components/paragraph/paragraph.tsx
import { Component, h, Host, Prop } from '@stencil/core';
import { clsx } from 'clsx';
export type ParagraphAs = 'p' | 'span';
export type ParagraphSize = 'lg' | 'md' | 'sm';
export type ParagraphAlign = 'start' | 'center' | 'end' | 'justify';
export type ParagraphWhitespace =
  | 'normal'
  | 'pre'
  | 'pre-wrap'
  | 'break-spaces';

function getSizeClass(as: ParagraphAs, size: ParagraphSize): string {
  switch (size) {
    case 'lg':
      return as === 'p' ? 'gi-paragraph-lg' : 'gi-span-lg';
    case 'sm':
      return as === 'p' ? 'gi-paragraph-sm' : 'gi-span-sm';
    default:
      return as === 'p' ? 'gi-paragraph-md' : 'gi-span-md';
  }
}

function getAlignClass(align: ParagraphAlign): string {
  switch (align) {
    case 'center':
      return 'gi-text-center';
    case 'end':
      return 'gi-text-end';
    case 'justify':
      return 'gi-text-justify';
    default:
      return 'gi-text-start';
  }
}

function getWhitespaceClass(ws: ParagraphWhitespace): string {
  switch (ws) {
    case 'pre':
      return 'gi-whitespace-pre';
    case 'pre-wrap':
      return 'gi-whitespace-pre-wrap';
    case 'break-spaces':
      return 'gi-whitespace-break-spaces';
    default:
      return 'gi-whitespace-normal';
  }
}

@Component({
  tag: 'govie-paragraph',
  scoped: true,
})
export class Paragraph {
  @Prop({ reflect: true }) as: ParagraphAs = 'p';
  @Prop({ reflect: true }) size: ParagraphSize = 'md';
  @Prop({ reflect: true }) align: ParagraphAlign = 'start';
  @Prop({ reflect: true }) whitespace: ParagraphWhitespace = 'normal';

  @Prop({ attribute: 'aria-label', reflect: true }) ariaLabel?: string;
  @Prop({ attribute: 'data-testid', reflect: true }) dataTestid?: string;

  render() {
    const common = {
      class: clsx(
        getSizeClass(this.as, this.size),
        getAlignClass(this.align),
        getWhitespaceClass(this.whitespace),
      ),
      'aria-label': this.ariaLabel,
      'data-testid': this.dataTestid,
    };

    return (
      <Host>
        {this.as === 'span' ? (
          <span {...common}>
            <slot />
          </span>
        ) : (
          <p {...common}>
            <slot />
          </p>
        )}
      </Host>
    );
  }
}
